### ISSUE TITLE
[REQUEST] Migrate docker-compose.yml for Compose V2

### ISSUE THREAD

**Issue by bhavik2936** [bhavik2936/docker-compose-files#7]
Please make sure to follow & check below prerequisites.

- [x] I checked the documentation and didn't find this feature
- [x] I checked to make sure that this feature has not already been requested

## Describe the Issue
As [**Compose v2**](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) now supports `compose` command; We shall adapt and migrate to new syntax for compose files.

## Expected Solution
Perform these two operations for below mentioned docker directories.
- [ ] remove version declaration (along with comment) from `docker-compose.yml`
- [ ] rename `docker-compose.yml` to `compose.yml`

#### Docker Directories
- mysql-phpmyadmin
- postgres-pgadmin
- elasticsearch-kibana

- [x] I will abide by the [code of conduct](https://github.com/bhavik2936/docker-compose-files/blob/main/.github/CODE_OF_CONDUCT.md).

**Comment by kishan-aghera** [comment]
Hi @bhavik2936 . I would like to work on this issue.
